import { Colors } from './colors';
import { FontFamily, TextStyles } from './typography';
import { Spacing, Radius } from './spacing';
import { Shadows } from './shadows';
export const theme = { colors: Colors, fonts: FontFamily, textStyles: TextStyles, spacing: Spacing, radius: Radius, shadows: Shadows } as const;
export type Theme = typeof theme;
export { Colors, FontFamily, TextStyles, Spacing, Radius, Shadows };
export type { ColorToken } from './colors';
export type { TextStyleToken } from './typography';
export type { SpacingToken, RadiusToken } from './spacing';
export type { ShadowToken } from './shadows';
